import os
import sys

# Находим путь к установленной библиотеке PyQt5 в вашей системе
import PyQt5
pyqt_path = os.path.dirname(PyQt5.__file__)
# Задаем системную переменную пути к плагинам
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = os.path.join(pyqt_path, 'Qt5', 'plugins', 'platforms')
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'convert.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setStyleSheet("background-color: #008080")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 141))
        self.frame.setStyleSheet("background-color: #efcdf4")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 20, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#008080")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(180, 60, 31, 51))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Documents/aip2/green.png"))
        self.label_2.setObjectName("label_2")
        self.input_cur = QtWidgets.QLineEdit(self.centralwidget)
        self.input_cur.setGeometry(QtCore.QRect(10, 150, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.input_cur.setFont(font)
        self.input_cur.setStyleSheet("background-color:#008080;border: 2px solid #efcdf4;\n"
"border-radius: 30 ;color: #efcdf4")
        self.input_cur.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cur.setObjectName("input_cur")
        self.input_sum = QtWidgets.QLineEdit(self.centralwidget)
        self.input_sum.setGeometry(QtCore.QRect(10, 220, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.input_sum.setFont(font)
        self.input_sum.setStyleSheet("background-color:#008080;border: 2px solid #efcdf4;\n"
"border-radius: 30 ;color: #efcdf4")
        self.input_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.input_sum.setObjectName("input_sum")
        self.output_cur = QtWidgets.QLineEdit(self.centralwidget)
        self.output_cur.setGeometry(QtCore.QRect(10, 290, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.output_cur.setFont(font)
        self.output_cur.setStyleSheet("background-color:#008080;border: 2px solid #efcdf4;\n"
"border-radius: 30 ;color: #efcdf4")
        self.output_cur.setAlignment(QtCore.Qt.AlignCenter)
        self.output_cur.setObjectName("output_cur")
        self.output_sum = QtWidgets.QLineEdit(self.centralwidget)
        self.output_sum.setGeometry(QtCore.QRect(10, 360, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.output_sum.setFont(font)
        self.output_sum.setStyleSheet("background-color:#008080;border: 2px solid #efcdf4;\n"
"border-radius: 30 ;color: #efcdf4")
        self.output_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.output_sum.setObjectName("output_sum")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 430, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {background-color:#008080;border: 2px solid #efcdf4;\n"
"border-radius: 30 ;color: #efcdf4;}   \n"
"QPushButton: pressed {background-color: #007070; }")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертатор валют"))
        self.pushButton.setText(_translate("MainWindow", "Конвертировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
