import os
import sys

# Находим путь к установленной библиотеке PyQt5 в вашей системе
import PyQt5

pyqt_path = os.path.dirname(PyQt5.__file__)
# Задаем системную переменную пути к плагинам
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = os.path.join(pyqt_path, 'Qt5', 'plugins', 'platforms')
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablumn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 381, 481))
        self.frame.setStyleSheet("\n"
"background-color: rgba(170, 170, 255, 50);\n"
"border: 3px solid  rgb(170, 0, 255, 50);\n"
"border-radius: 30 ;\n"
"color: #efcdf4")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 341, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.btn1 = QtWidgets.QPushButton(self.frame)
        self.btn1.setGeometry(QtCore.QRect(20, 120, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn1.setObjectName("btn1")
        self.btn4 = QtWidgets.QPushButton(self.frame)
        self.btn4.setGeometry(QtCore.QRect(20, 210, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn4.setObjectName("btn4")
        self.btn7 = QtWidgets.QPushButton(self.frame)
        self.btn7.setGeometry(QtCore.QRect(20, 300, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn7.setObjectName("btn7")
        self.btn2 = QtWidgets.QPushButton(self.frame)
        self.btn2.setGeometry(QtCore.QRect(140, 120, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn2.setObjectName("btn2")
        self.btn5 = QtWidgets.QPushButton(self.frame)
        self.btn5.setGeometry(QtCore.QRect(140, 210, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn5.setObjectName("btn5")
        self.btn8 = QtWidgets.QPushButton(self.frame)
        self.btn8.setGeometry(QtCore.QRect(140, 300, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn8.setObjectName("btn8")
        self.btn3 = QtWidgets.QPushButton(self.frame)
        self.btn3.setGeometry(QtCore.QRect(260, 120, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn3.setObjectName("btn3")
        self.btn6 = QtWidgets.QPushButton(self.frame)
        self.btn6.setGeometry(QtCore.QRect(260, 210, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn6.setObjectName("btn6")
        self.btn1_9 = QtWidgets.QPushButton(self.frame)
        self.btn1_9.setGeometry(QtCore.QRect(260, 300, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn1_9.setFont(font)
        self.btn1_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.btn1_9.setObjectName("btn1_9")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 390, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 390, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(184, 192, 255, 255), stop:1 rgba(255, 212, 187, 255));\n"
"\n"
"border: 3px solid  rgb(170, 0, 255);\n"
"border-radius: 20 ;\n"
"color: rgb(170, 0, 255)")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn1_9.setText(_translate("MainWindow", "9"))
        self.pushButton.setText(_translate("MainWindow", "умножить"))
        self.pushButton_2.setText(_translate("MainWindow", "очистить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
